### ISSUE TITLE
CurrencyLayer isn't working with a free account

### ISSUE THREAD

**Issue by nDmitry** [tajawal/swap#2]
Hi, trying to set up CurrencyLayer with my free account, but it's failing with error `Access Restricted - Your current Subscription Plan does not support this API Function.`.

It seems like the API endpoint this library is using is not for free accounts:

```
$ curl "http://apilayer.net/api/convert?access_key=[key]&from=USD&to=RUB&amount=1&format=1" 
{
  "success":false,
  "error":{
    "code":105,
    "info":"Access Restricted - Your current Subscription Plan does not support this API Function."
  }
}
```

While another is working:

```
$ curl "http://apilayer.net/api/live?access_key=[key]&currencies=RUB&source=USD&format=1"
{
  "success":true,
  "terms":"https:\/\/currencylayer.com\/terms",
  "privacy":"https:\/\/currencylayer.com\/privacy",
  "timestamp":1456649229,
  "source":"USD",
  "quotes":{
    "USDRUB":76.354504
  }
}
```

**Comment by khurrumqureshi** [comment]
@nDmitry You are exactly right I am using api endpoint which only works for paid account. But I will change it to work for free account as well. 

Thanks for your input.

**Comment by khurrumqureshi** [comment]
Its fixed now..

**Comment by nDmitry** [comment]
Great, thanks!

**Comment by sharathsama** [comment]
I am also getting same error with free account

"success":false,"error":{"code":105,"info":"Access Restricted - Your current Subscription Plan does not support this API Function."

**Comment by glowingemp103** [comment]
I am also getting same above error
{
    "success": false,
    "error": {
        "code": 105,
        "info": "Access Restricted - Your current Subscription Plan does not support HTTPS Encryption."
    }
}

**Comment by MayurRaval** [comment]
I just created free account and tried to check API response and response is 

{
  "success": false,
  "error": {
    "code": 105,
    "info": "Access Restricted - Your current Subscription Plan does not support HTTPS Encryption."
  }
}

**Comment by haseebjaved1** [comment]
use http in place of https

**Comment by jerrybaghel396** [comment]
> use http in place of https

that work thanks
